#!/bin/sh
# Install some git hooks.  Run this when cloning a new repo.

cd .git/hooks
for f in ../../git-hooks/*; do
    if [[ $(basename $f) != install ]]; then
        ln -sf $f
    fi
done

# pre-commit uses this.
git config core.whitespace trailing-space,tab-in-indent
