#!/usr/bin/env zsh
# Run after git checkout and update the tags file.
# Put this in .git/hooks

set -eu

old=$1
new=$2
# is_branch=$2 # 1 if branch, 2 if file

# filter out only the changed files
changed=($(git diff --name-only $old $new))

echo "$old -> $new: $changed"

if [[ ! -r tags ]]; then
    tools/init_tags
elif [[ ${#changed} -gt 0 ]]; then
    grep -v -F --regexp=${^changed} tags >tags.tmp
    mv tags.tmp tags

    # Retag all hs files except the ones that were deleted.
    modified=($(git diff --name-only --diff-filter=d $old $new))
    # Filter *.hs, since grep returns non-zero for no matches.
    modified=(${(M)modified:#*.hs})
    echo "modified: $modified"
    tools/init_tags $modified
fi
