#!/bin/sh

# I don't know what changed after a merge, so I need to regenerate tags.
# I should probably do this after a branch checkout too, but let's assume
# branches are mostly the same for now.
rm -f tags
