#!/bin/zsh -e
# Copyright 2013 Evan Laforge
# This program is distributed under the terms of the GNU General Public
# License 3.0, see COPYING or http://www.gnu.org/licenses/gpl-3.0.txt

test_outputs=("$@")

echo -n '\nTests complete.  Failures:\n'
cat $test_outputs | test/extract_failures.py
# These magic prefixes are in Util.Test and Util.RunTests.
passes=$(grep '^++->' $test_outputs | wc -l)
failures=$(grep '^__->' $test_outputs | wc -l)
tests=$(grep '^===> run-test' $test_outputs | wc -l)
echo $failures failed / $passes passed / $tests tests
