#!/bin/zsh
# Copyright 2013 Evan Laforge
# This program is distributed under the terms of the GNU General Public
# License 3.0, see COPYING or http://www.gnu.org/licenses/gpl-3.0.txt

test_output=$1

echo -n '\nTests complete.  Failures:\n'
test/extract_failures.py <$test_output
# These magic prefixes are in Util.Test and Util.RunTests.
passes=$(grep '^++->' $test_output | wc -l)
failures=$(grep '^__->' $test_output | wc -l)
tests=$(grep '^===> run-test' $test_output | wc -l)
echo $failures failed / $passes passed / $tests tests
