#!/bin/zsh

# Run tests given in prefixes.  If some of them require init, run each in a
# separate process.
# Redirect stderr to test.output.
# Grep for failures.

# TODO: display warn and error log msgs

run_tests=test_obj/RunTests
test_output=test.output
prefixes=("$@")

init_tests=($($run_tests -list $prefixes | grep '^init-'))
direct_tests=($($run_tests -list $prefixes | grep '^direct-'))

rm -f $test_output

function run() {
    "$@"
    local r=$?
    if [[ $r -ne 0 ]]; then
        echo __: cmd returned $r: "$@"
    fi
}

if [ "$direct_tests" ]; then
    run $run_tests $direct_tests 2>>$test_output
fi
for test in $init_tests; do
    run $run_tests $test
done

grep '^\*\*' $test_output
failures=$(grep '^\*\*' $test_output | wc -l)
echo $failures failures

echo Generating hpc markup...
hpc markup --destdir=hpc RunTests | grep -v Writing
# I'm more used to typing index.html
(cd hpc && ln -s hpc_index.html index.html)

exit $failures
