#!/bin/zsh

# Run tests given in prefixes.  If some of them require init, run each in a
# separate process.
# Redirect stderr to test.output.
# Grep for failures.

# TODO: display warn and error log msgs

run_tests=test_obj/RunTests

# This is appended to.  It should be reset along with the coverage data every
# time test_obj/RunTests is built.
test_output=test.output

prefixes=("$@")
flags=()
if [[ $prefixes[0] = '--skip' ]]; then
    flags=(--skip)
    shift
fi

init_tests=($($run_tests --list $prefixes | grep '^init-'))
direct_tests=($($run_tests --list $prefixes | grep '^direct-'))

function run() {
    "$@"
    local r=$?
    if [[ $r -ne 0 ]]; then
        echo __: cmd returned $r: "$@"
    fi
}

if [ "$direct_tests" ]; then
    run $run_tests $flags $direct_tests |& tee -a $test_output
fi
for test in $init_tests; do
    run $run_tests $flags $test |& tee -a $test_output
done

echo -n '\nTests complete.  Results:\n'
test/extract_failures.py <$test_output
passes=$(grep '^++' $test_output | wc -l)
failures=$(grep '^__' $test_output | wc -l)
echo $failures failed / $passes passed

echo Generating hpc markup...
hpc markup --destdir=hpc RunTests | grep -v Writing
# I'm more used to typing index.html
(cd hpc && ln -fs hpc_index.html index.html)

exit $failures
