#!/bin/sh
# michael sweet posted this to the fltk mailing list

if test $# != 1; then
       echo Usage: makebundle.sh filename
       exit 1
fi

name="$1"
id=`echo $name | tr ' ' '_'`

# Make the bundle directory and move the executable there
rm -rf "$name.app/Contents/MacOS"
mkdir -p "$name.app/Contents/MacOS"
mv "$name" "$name.app/Contents/MacOS"

# Make a shell script that runs the bundled executable
# echo "#!/bin/sh" >"$name"
# echo "exec '$name.app/Contents/MacOS/$name'" '$*' >>"$name"
# chmod +x "$name"

# Make the simplest Info.plist needed for an application
cat >"$name.app/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<plist version="0.9">
    <dict>
       <key>CFBundleInfoDictionaryVersion</key>
       <string>6.0</string>
       <key>CFBundleExecutable</key>
       <string>$name</string>
       <key>CFBundleIdentifier</key>
       <string>org.fltk.$id</string>
       <key>CFBundleName</key>
       <string>$name</string>
       <key>CFBundlePackageType</key>
       <string>APPL</string>
    </dict>
</plist>
EOF
