#!/bin/zsh
# I keep data files in a separate directory, to keep it out of source
# control, and so I can share the data across multiple clones and branches.

data=../data

for dir in im inst_db ness-data prof save; do
    ln -s $data/$dir
done
