-- Copyright 2017 Evan Laforge
-- This program is distributed under the terms of the GNU General Public
-- License 3.0, see COPYING or http://www.gnu.org/licenses/gpl-3.0.txt

-- automatically generated by extract_korvais
-- | Collect korvais into one database.
-- This is automatically generated, but checked in for convenience.
-- Don't edit it directly.  Any modifications to the the source
-- directory should cause it to be regenerated.
module Derive.Solkattu.All where
import qualified Derive.Solkattu.Korvai as Korvai
import Derive.Solkattu.Metadata
import qualified Derive.Solkattu.Score.Mridangam2013
import qualified Derive.Solkattu.Score.Mridangam2017
import qualified Derive.Solkattu.Score.Solkattu2013
import qualified Derive.Solkattu.Score.Solkattu2014
import qualified Derive.Solkattu.Score.Solkattu2016
import qualified Derive.Solkattu.Score.Solkattu2017


korvais :: [Korvai.Korvai]
korvais =
    [ set_location ("Derive.Solkattu.Score.Mridangam2013",16,"dinnagina_sequence") Derive.Solkattu.Score.Mridangam2013.dinnagina_sequence
    , set_location ("Derive.Solkattu.Score.Mridangam2013",89,"t_16_11_14") Derive.Solkattu.Score.Mridangam2013.t_16_11_14
    , set_location ("Derive.Solkattu.Score.Mridangam2013",95,"t_17_02_13") Derive.Solkattu.Score.Mridangam2013.t_17_02_13
    , set_location ("Derive.Solkattu.Score.Mridangam2013",108,"din_nadin") Derive.Solkattu.Score.Mridangam2013.din_nadin
    , set_location ("Derive.Solkattu.Score.Mridangam2013",115,"nadin_ka") Derive.Solkattu.Score.Mridangam2013.nadin_ka
    , set_location ("Derive.Solkattu.Score.Mridangam2013",120,"nadindin") Derive.Solkattu.Score.Mridangam2013.nadindin
    , set_location ("Derive.Solkattu.Score.Mridangam2013",138,"nadindin_negative") Derive.Solkattu.Score.Mridangam2013.nadindin_negative
    , set_location ("Derive.Solkattu.Score.Mridangam2013",151,"namita_dimita") Derive.Solkattu.Score.Mridangam2013.namita_dimita
    , set_location ("Derive.Solkattu.Score.Mridangam2013",168,"janahan_exercise") Derive.Solkattu.Score.Mridangam2013.janahan_exercise
    , set_location ("Derive.Solkattu.Score.Mridangam2013",172,"nakanadin") Derive.Solkattu.Score.Mridangam2013.nakanadin
    , set_location ("Derive.Solkattu.Score.Mridangam2013",178,"p16_12_06_sriram2") Derive.Solkattu.Score.Mridangam2013.p16_12_06_sriram2
    , set_location ("Derive.Solkattu.Score.Mridangam2013",186,"p16_12_06_janahan1") Derive.Solkattu.Score.Mridangam2013.p16_12_06_janahan1
    , set_location ("Derive.Solkattu.Score.Mridangam2013",193,"p16_12_06_janahan2") Derive.Solkattu.Score.Mridangam2013.p16_12_06_janahan2
    , set_location ("Derive.Solkattu.Score.Mridangam2013",205,"farans") Derive.Solkattu.Score.Mridangam2013.farans
    , set_location ("Derive.Solkattu.Score.Mridangam2013",251,"eddupu6") Derive.Solkattu.Score.Mridangam2013.eddupu6
    , set_location ("Derive.Solkattu.Score.Mridangam2013",262,"eddupu10") Derive.Solkattu.Score.Mridangam2013.eddupu10
    , set_location ("Derive.Solkattu.Score.Mridangam2017",11,"c_17_07_10") Derive.Solkattu.Score.Mridangam2017.c_17_07_10
    , set_location ("Derive.Solkattu.Score.Solkattu2013",21,"c_13_07_23") Derive.Solkattu.Score.Solkattu2013.c_13_07_23
    , set_location ("Derive.Solkattu.Score.Solkattu2013",28,"c_13_08_14") Derive.Solkattu.Score.Solkattu2013.c_13_08_14
    , set_location ("Derive.Solkattu.Score.Solkattu2013",68,"c_yt1") Derive.Solkattu.Score.Solkattu2013.c_yt1
    , set_location ("Derive.Solkattu.Score.Solkattu2013",79,"c_13_10_29") Derive.Solkattu.Score.Solkattu2013.c_13_10_29
    , set_location ("Derive.Solkattu.Score.Solkattu2013",93,"c_13_11_05") Derive.Solkattu.Score.Solkattu2013.c_13_11_05
    , set_location ("Derive.Solkattu.Score.Solkattu2013",101,"c_13_11_12") Derive.Solkattu.Score.Solkattu2013.c_13_11_12
    , set_location ("Derive.Solkattu.Score.Solkattu2013",118,"c_13_12_11") Derive.Solkattu.Score.Solkattu2013.c_13_12_11
    , set_location ("Derive.Solkattu.Score.Solkattu2013",151,"c_nnnd") Derive.Solkattu.Score.Solkattu2013.c_nnnd
    , set_location ("Derive.Solkattu.Score.Solkattu2013",170,"k1_1") Derive.Solkattu.Score.Solkattu2013.k1_1
    , set_location ("Derive.Solkattu.Score.Solkattu2013",187,"k1_2") Derive.Solkattu.Score.Solkattu2013.k1_2
    , set_location ("Derive.Solkattu.Score.Solkattu2013",200,"k1_3") Derive.Solkattu.Score.Solkattu2013.k1_3
    , set_location ("Derive.Solkattu.Score.Solkattu2013",234,"k3s") Derive.Solkattu.Score.Solkattu2013.k3s
    , set_location ("Derive.Solkattu.Score.Solkattu2013",279,"t1s") Derive.Solkattu.Score.Solkattu2013.t1s
    , set_location ("Derive.Solkattu.Score.Solkattu2013",301,"t2s") Derive.Solkattu.Score.Solkattu2013.t2s
    , set_location ("Derive.Solkattu.Score.Solkattu2013",334,"t3s") Derive.Solkattu.Score.Solkattu2013.t3s
    , set_location ("Derive.Solkattu.Score.Solkattu2013",371,"t4s") Derive.Solkattu.Score.Solkattu2013.t4s
    , set_location ("Derive.Solkattu.Score.Solkattu2013",395,"t4s2") Derive.Solkattu.Score.Solkattu2013.t4s2
    , set_location ("Derive.Solkattu.Score.Solkattu2013",420,"t4s3") Derive.Solkattu.Score.Solkattu2013.t4s3
    , set_location ("Derive.Solkattu.Score.Solkattu2013",443,"t5s") Derive.Solkattu.Score.Solkattu2013.t5s
    , set_location ("Derive.Solkattu.Score.Solkattu2013",499,"koraippu_misra") Derive.Solkattu.Score.Solkattu2013.koraippu_misra
    , set_location ("Derive.Solkattu.Score.Solkattu2013",538,"tir_18") Derive.Solkattu.Score.Solkattu2013.tir_18
    , set_location ("Derive.Solkattu.Score.Solkattu2014",17,"c_14_01_01") Derive.Solkattu.Score.Solkattu2014.c_14_01_01
    , set_location ("Derive.Solkattu.Score.Solkattu2014",42,"c_14_01_14") Derive.Solkattu.Score.Solkattu2014.c_14_01_14
    , set_location ("Derive.Solkattu.Score.Solkattu2014",78,"c_14_02_05") Derive.Solkattu.Score.Solkattu2014.c_14_02_05
    , set_location ("Derive.Solkattu.Score.Solkattu2014",119,"c_13_11_19") Derive.Solkattu.Score.Solkattu2014.c_13_11_19
    , set_location ("Derive.Solkattu.Score.Solkattu2014",155,"c_mohra") Derive.Solkattu.Score.Solkattu2014.c_mohra
    , set_location ("Derive.Solkattu.Score.Solkattu2014",172,"c_mohra2") Derive.Solkattu.Score.Solkattu2014.c_mohra2
    , set_location ("Derive.Solkattu.Score.Solkattu2014",190,"c_mohra_youtube") Derive.Solkattu.Score.Solkattu2014.c_mohra_youtube
    , set_location ("Derive.Solkattu.Score.Solkattu2016",13,"c_16_09_28") Derive.Solkattu.Score.Solkattu2016.c_16_09_28
    , set_location ("Derive.Solkattu.Score.Solkattu2016",39,"c_16_12_06_sriram1") Derive.Solkattu.Score.Solkattu2016.c_16_12_06_sriram1
    , set_location ("Derive.Solkattu.Score.Solkattu2017",20,"koraippu_janahan") Derive.Solkattu.Score.Solkattu2017.koraippu_janahan
    , set_location ("Derive.Solkattu.Score.Solkattu2017",79,"e_spacing") Derive.Solkattu.Score.Solkattu2017.e_spacing
    , set_location ("Derive.Solkattu.Score.Solkattu2017",94,"c_17_02_06") Derive.Solkattu.Score.Solkattu2017.c_17_02_06
    , set_location ("Derive.Solkattu.Score.Solkattu2017",104,"c_17_03_20") Derive.Solkattu.Score.Solkattu2017.c_17_03_20
    , set_location ("Derive.Solkattu.Score.Solkattu2017",127,"c_17_04_04") Derive.Solkattu.Score.Solkattu2017.c_17_04_04
    , set_location ("Derive.Solkattu.Score.Solkattu2017",153,"c_17_04_23") Derive.Solkattu.Score.Solkattu2017.c_17_04_23
    , set_location ("Derive.Solkattu.Score.Solkattu2017",180,"c_17_05_10") Derive.Solkattu.Score.Solkattu2017.c_17_05_10
    , set_location ("Derive.Solkattu.Score.Solkattu2017",228,"c_17_05_11") Derive.Solkattu.Score.Solkattu2017.c_17_05_11
    , set_location ("Derive.Solkattu.Score.Solkattu2017",256,"c_17_05_19") Derive.Solkattu.Score.Solkattu2017.c_17_05_19
    , set_location ("Derive.Solkattu.Score.Solkattu2017",262,"c_17_05_19_janahan") Derive.Solkattu.Score.Solkattu2017.c_17_05_19_janahan
    , set_location ("Derive.Solkattu.Score.Solkattu2017",285,"c_17_06_02_janahan") Derive.Solkattu.Score.Solkattu2017.c_17_06_02_janahan
    , set_location ("Derive.Solkattu.Score.Solkattu2017",298,"c_17_06_15") Derive.Solkattu.Score.Solkattu2017.c_17_06_15
    , set_location ("Derive.Solkattu.Score.Solkattu2017",313,"c_17_06_19") Derive.Solkattu.Score.Solkattu2017.c_17_06_19
    , set_location ("Derive.Solkattu.Score.Solkattu2017",341,"c_17_06_19_koraippu") Derive.Solkattu.Score.Solkattu2017.c_17_06_19_koraippu
    , set_location ("Derive.Solkattu.Score.Solkattu2017",366,"c_17_07_13") Derive.Solkattu.Score.Solkattu2017.c_17_07_13
    , set_location ("Derive.Solkattu.Score.Solkattu2017",460,"c_17_07_19") Derive.Solkattu.Score.Solkattu2017.c_17_07_19
    ]
