#!/bin/zsh
# Snapshot the contants of save/ to $dir.
#
# This is not just for backups, but so I can run verify_performance with the
# past version of each score, to see performance over time.
#
# git-annex solves this problem in a more sophisticated way, but of course it
# only works for git.

set -e # quit on error
set -x # verbose

dir=../data/save-backup
tgz=$dir/$(date +%y-%m-%d_%H:%M:%S).tgz

tar -cLzf $tgz save
ls -lh $tgz
