#!/usr/bin/env zsh
#
# Upload build deps to cachix.

set -eux

args=(
    --arg withDocs true
    --arg withIm true
    --arg withDevelopment false
)
nix-build $args -A buildEnv | cachix push elaforge
