#!/usr/bin/env zsh
# Copyright 2013 Evan Laforge
# This program is distributed under the terms of the GNU General Public
# License 3.0, see COPYING or http://www.gnu.org/licenses/gpl-3.0.txt

out_dir=$1
shift
fs=("$@")

# For some reason hscolour changed its binary name.
if whence hscolour; then
  hscolour=hscolour
elif whence HsColour; then
  hscolour=HsColour
else
  echo hscolour binary not found
  exit 1
fi

for f in $fs; do
    dir=$(dirname  $f)
    mkdir -p $out_dir/$dir
    # Apparently there's no way to build in the CSS or configure the css link,
    # and .hscolour is limited to ugly terminal colors, so just copy the CSS
    # over.
    cp tools/hscolour.css $out_dir/$dir
    echo $hscolour -anchor -css -o$out_dir/${f%.hs*}.html $f
    $hscolour -anchor -css -o$out_dir/${f%.hs*}.html $f
done
