#!/bin/zsh
# Copyright 2013 Evan Laforge
# This program is distributed under the terms of the GNU General Public
# License 3.0, see COPYING or http://www.gnu.org/licenses/gpl-3.0.txt

if [[ $# -ne 2 ]]; then
    echo usage: $0 input output.html
    exit 1
fi

haddock_dir=../haddock
in=$1
out=$2

build/opt/linkify $haddock_dir $in \
    | pandoc --standalone --from=markdown --to=html >$out
