#!/bin/sh
# Copyright 2013 Evan Laforge
# This program is distributed under the terms of the GNU General Public
# License 3.0, see COPYING or http://www.gnu.org/licenses/gpl-3.0.txt

dir=$(basename $(pwd))
cd ..
tar --exclude $dir/build/ --exclude $dir/.hpc --exclude $dir/data \
    -czvf $dir.tgz $dir
