#!/usr/bin/env zsh

flags=${1?}
shift

. tools/use-stack

args=(
    # Turn off idle time GC, since it causes input lag when lots of modules
    # are loaded.
    +RTS -I0 -RTS
    -j$(tools/ncpus)

    # This bit of zsh insanity reads newline separated words, so args with
    # spaces work.
    "${(@f)$(cat $flags)}"
)

# Don't use ghci since I run this from a script called ghci, and I don't
# want to get in a loop.
exec ghc --interactive $args "$@"
