#!/bin/zsh
# Copyright 2013 Evan Laforge
# This program is distributed under the terms of the GNU General Public
# License 3.0, see COPYING or http://www.gnu.org/licenses/gpl-3.0.txt

# Diff two binary files.

alias od='od -v -A x -taxC'

od $1 >/tmp/$(basename $1).od
od $2 >/tmp/$(basename $2).od
opendiff /tmp/$(basename $1).od /tmp/$(basename $2).od
