#!/usr/bin/env zsh
# Sohpisticated mixdown technology using sox.

set -eu
if [[ $# -ne 1 ]]; then
    echo "usage: $0 im/cache/score/path/block"
    exit 1
fi
base_dir=$1
out=im/mix/$(basename $base_dir)

set -x

rm -rf $out
mkdir -p $out

for inst in $base_dir/*; do
    sox -V1 $inst/*.wav $out/$(basename $inst).wav
done

outs=($out/*.wav)
if [[ ${#outs} -gt 1 ]]; then
    sox --combine mix $out/*.wav $out/mixed.wav
else
    mv $outs[1] $out/mixed.wav
fi
lame -h -b160 $out/mixed.wav
