#!/usr/bin/env zsh
# Sohpisticated mixdown technology.

set -eu
if [[ $# -ne 2 ]]; then
    echo "usage: $0 name im/cache/score/path/block"
    exit 1
fi
name=$1
base_dir=$2
out=im/mix/$name

mkdir -p im/mix

set -x

run build/opt/mixdown $out.wav $base_dir/*
lame -h -b160 $out.wav
rm $out.wav
