#!/bin/zsh
# Copyright 2013 Evan Laforge
# This program is distributed under the terms of the GNU General Public
# License 3.0, see COPYING or http://www.gnu.org/licenses/gpl-3.0.txt

# fast-tags wrapper to generate tags automatically if there are none.

fn=$1
flags=(
    --fully-qualified # I use qualified_tag.py
)
if [[ ! -r tags ]]; then
    echo Generating tags from scratch...
    exec fast-tags $flags $(tools/all_hs.py)
else
    exec fast-tags $flags $fn
fi
