#!/bin/zsh
# fast-tags wrapper to generate tags automatically if there are none.

fn=$1
if [[ ! -r tags ]]; then
    echo Generating tags from scratch...
    exec fast-tags $(tools/all_hs.py)
else
    exec fast-tags $fn
fi
