#!/usr/bin/env zsh
# Compile play_cache and move into place.

set -eux
vst=~/Library/Audio/Plug-Ins/VST

vsts=(
    play_cache
    panner
)

bin/mk build/opt/${^vsts}

rm -rf $vst/${^vsts}.vst
cp -r build/opt/${^vsts}.vst $vst
