#!/bin/zsh
# Compile a list of targets.
# If I just put the targets on in the dependency, make will want to run it
# all in parallel, which results in endless recompilation as the ghcs walk on
# each other.  So explicitly run in sequence and disable jobs.

for target in $*; do
    echo Making $target...
    if ! make -j1 $target; then break; fi
done
