#!/usr/bin/env zsh
# Copyright 2013 Evan Laforge
# This program is distributed under the terms of the GNU General Public
# License 3.0, see COPYING or http://www.gnu.org/licenses/gpl-3.0.txt

# Based on a script michael sweet posted to the fltk mailing list.

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 filename [icon.icns] [args]"
    exit 1
fi

binpath=$1
icon=$2
args=$3
name=$(basename "$binpath")
id=elaforge.seq.$(echo "$name" | tr ' ' _)
bindir=$binpath.app/Contents/MacOS

# Make a shell script that runs the bundled executable
# Use $(basename $0) internally so you can rename it.
cat >"$binpath.run" <<EOF
#!/bin/sh
dir=\$(dirname "\$0")
bin=\$(basename "\$0")
exec "\$dir/\$bin.app/Contents/MacOS/$name" $args "\$@"
EOF
chmod +x "$binpath.run"

# Make sure this script is idempotent.
if [[ $(head -c2 $binpath) = '#!' ]] then
    echo replacing shell script
    mv $binpath.run $binpath
else
    rm -rf "$bindir"
    mkdir -p "$bindir"
    mv "$binpath" "$bindir"
    mv "$binpath.run" "$binpath"
    if [[ -n $icon ]]; then
        mkdir -p $binpath.app/Contents/Resources
        cp $icon $binpath.app/Contents/Resources/icon
        icon_info="<key>CFBundleIconFile</key> <string>icon</string>"
    fi
fi

# Make the simplest Info.plist needed for an application
cat >"$binpath.app/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<plist version="0.9">
    <dict>
        <key>CFBundleInfoDictionaryVersion</key>
            <string>6.0</string>
        <key>CFBundleExecutable</key>
            <string>$name</string>
        <key>CFBundleIdentifier</key>
            <string>$id</string>
        <key>CFBundleName</key>
            <string>$name</string>
        <key>CFBundlePackageType</key>
            <string>APPL</string>
        <key>NSHighResolutionCapable</key><true/>
        $icon_info
    </dict>
</plist>
EOF
