#!/bin/zsh
# based on a script michael sweet posted to the fltk mailing list

if test $# != 1; then
    echo Usage: $0 filename
    exit 1
fi

binpath="$1"
name=$(basename "$binpath")
id=elaforge.seq.$(echo "$name" | tr ' ' _)
bindir="$binpath.app/Contents/MacOS"

if [[ $name = seq ]]; then
    extra_args=(+RTS -N2 -RTS)
fi

# Make a shell script that runs the bundled executable
cat >"$binpath.run" <<EOF
#!/bin/sh
dir=\$(dirname "\$0")
exec "\$dir/$name.app/Contents/MacOS/$name" $extra_args "\$@"
EOF
chmod +x "$binpath.run"

# Make sure the script is idempotent since make likes to run it due to .PHONY.
if cmp --silent "$binpath.run" "$binpath"; then
    rm "$binpath.run"
else
    rm -rf "$bindir"
    mkdir -p "$bindir"
    mv "$binpath" "$bindir"
    mv "$binpath.run" "$binpath"
fi

# Make the simplest Info.plist needed for an application
cat >"$binpath.app/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<plist version="0.9">
    <dict>
       <key>CFBundleInfoDictionaryVersion</key>
       <string>6.0</string>
       <key>CFBundleExecutable</key>
       <string>$name</string>
       <key>CFBundleIdentifier</key>
       <string>$id</string>
       <key>CFBundleName</key>
       <string>$name</string>
       <key>CFBundlePackageType</key>
       <string>APPL</string>
    </dict>
</plist>
EOF
