#!/usr/bin/env zsh
# Enter a nix shell.

args=(
    --attr buildEnv
    --arg withDocs true
    # --arg withDevelopment true
)

# nix-shell is really slow, because eval is really slow.
# If I print this out I can copy paste into another terminal to get
# a shell more quickly.
drv=$(nix-instantiate $args)
echo cd $PWD '&& nix-shell --run "exec $SHELL"' $drv
nix-shell --run "exec $SHELL" $drv
