#!/usr/bin/env zsh
# Copyright 2018 Evan Laforge
# This program is distributed under the terms of the GNU General Public
# License 3.0, see COPYING or http://www.gnu.org/licenses/gpl-3.0.txt

# Run profile_verify.py for a standard set of scores.

scores=(
    save/complete/wayang/p1
    save/complete/wayang/cerucuk-punyah.state
    save/complete/bloom
    save/complete/hex
    save/complete/viola-sonata
    save/complete/squart/6
)

tools/profile_verify.py $scores
