#!/bin/zsh

gitlab=git@gitlab.com:elaforge/karya.git
github=git@github.com:elaforge/karya.git

# gitlab is private and may be rebased
git push --all --force $gitlab

# github is public and I shouldn't rebase it
git push $github master
