#!/bin/zsh
# Initialize a new install with an empty default config.
#
# I keep data files in a separate directory, to keep it out of source
# control, and so I can share the data across multiple clones and branches.

export data=${data:-../data}

echo "Making $data to store local data."
echo "If you want a different place, quit and rerun with data=whatever $0"
if ! read -q '?ok (y/n) '; then
    exit 1
fi

mkdir -p $data

export hs_dir=User/Empty
export hs_package=User.Empty

tools/do-setup

cp data/default.save save/
