#!/bin/zsh
# Initialize a new install with an empty default config.  This copies
# template config from User/Empty/ to Local/, where you can edit it and
# keep your changes out of source control.
#
# I keep data files in a separate directory, to keep it out of source
# control, and so I can share the data across multiple clones and branches.

export data=${data:-../data}

if [[ ! -e $data ]]; then
    echo "Making $data to store local data."
    echo "If you want a different place, quit and rerun with data=whatever $0"
    if ! read -q '?ok (y/n) '; then
        exit 1
    fi
fi

mkdir -p $data

export hs_dir=User/Empty
export hs_package=User.Empty

tools/do-setup
