#!/bin/zsh
# Update all saved states to the latest version.

setopt err_exit
setopt extended_glob

update=build/opt/update

bin/mk $update
mkdir -p save.new

for f in save/*; do
    to=save.new/${f#save/}
    if [[ $to = *.git ]]; then
        # update flattens it, so it's not a .git anymore.
        to=${to%git}ex-git
    fi
    echo "$f -> $to"
    # *_ly contains saved lilypond scores.
    if [[ $f = save/README || $f = *_ly* ]]; then
        cp -r $f $to
    else
        $update $f $to
    fi
done

mv save save.old
mv save.new save
