# https://nix.dev/tutorials/continuous-integration-github-actions.html

name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          # nix_path: nixpkgs=channel:nixos-unstable
          nix_path: nixpkgs=channel:nixos-19.09
          # nix_path: nixpkgs=channel:nixos-20.09
          # extra_nix_config: append to /etc/nix/nix.conf
      - uses: cachix/cachix-action@v8
        with:
          name: elaforge
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          # I think it's binaryCaches.secretKey?
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

      # 19.09.2522.75f4ba05c63
      # but mine is 19.09pre-git
      # - run: nix-instantiate --eval -E "(import <nixpkgs> {}).lib.version"

      # Build in advance and make sure the result is cached immediately, since
      # I think it won't upload if later steps fail.
      # - run: nix build -L -f default.nix --arg isCi true buildEnv
      # - run: cachix push elaforge $(readlink result)
      - run: nix/run_ci
